name: Publish package

defaults:
  run:
    working-directory: Hello.World.Lfraile/Hello.World.Lfraile
  
on:
  workflow_dispatch:
  push:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2
        
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3.0.3
        with:
          dotnet-version: 6.x
      
      - run: |
          dotnet build -c Release -o ./output          
      
      - run: |
          dotnet nuget add source --username USERNAME --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/lfraileorg/index.json"
          dotnet nuget push "./output/*.nupkg" --source "github" --skip-duplicate --api-key ${{ secrets.GITHUB_TOKEN }}          
      
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:          
          name: output
          path: Hello.World.Lfraile/Hello.World.Lfraile/output/**
          
      - name: Publish Symbols
        uses: microsoft/action-publish-symbols@v2.1.6
        with:      
          accountName: lfrailepublic          
          personalAccessToken: ${{ secrets.PAT_AZDO }}
          searchPattern: '**/Hello.World.Lfraile/output/*.pdb'
