name: Publish package

defaults:
  run:
    working-directory: Hello.World.Lfraile/Hello.World.Lfraile
  
on:
  workflow_dispatch:
  push:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3.0.3
        with:
          # Optional SDK version(s) to use. If not provided, will install global.json version when available. Examples: 2.2.104, 3.1, 3.1.x, 3.x
          dotnet-version: 6.x
      - run: |
          dotnet build -c Release -o ./output
          dotnet nuget add source --username USERNAME --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/lfraileorg/index.json"
          dotnet nuget push "./output/*.nupkg" --source "github" --skip-duplicate --api-key ${{ secrets.GITHUB_TOKEN }}
          dotnet nuget push "./output/*.snupkg" --source "github" --api-key ${{ secrets.GITHUB_TOKEN }}
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:          
          name: output
          # A file, directory or wildcard pattern that describes what to upload
          path: Hello.World.Lfraile/Hello.World.Lfraile/output/**
          # The desired behavior if no files are found using the provided path.
     
