name: Wiki publish

on:
  gollum:
  workflow_dispatch:    
  push:
    paths: .github/workflows/wiki.yml
  
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo ${{ github.server_url }}/${{github.repository}}.wiki.git
    - run: |
        git clone ${{ github.server_url }}/${{github.repository}}.wiki.git
        ls
